name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    runs-on: windows-latest

    steps:
      - name: Set git to checkout as is, commit LF
        run: git config --global core.autocrlf input

      - uses: actions/checkout@v2

      - name: Cargo Test
        run: cargo test --workspace -- --nocapture

      - name: Cargo Format Check
        run: cargo fmt -- --check

      - name: Cargo Clippy Check
        run: cargo clippy --all-features --workspace -- -D warnings

      - name: Cargo Sort Check
        run: cargo install cargo-sort --debug && cargo-sort --check --workspace


  cargo_sort_autofix:
    name: Cargo Sort Autofix
    runs-on: windows-latest
    if: github.event_name != 'release'
    steps:
      - name: Set git to checkout as is, commit LF
        run: git config --global core.autocrlf input

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install cargo-sort
        run: cargo install cargo-sort --debug

      - name: Run cargo sort
        run: cargo sort --workspace

      - name: Show updated Cargo.toml
        run: |
          echo '--- Cargo.toml after cargo sort ---'
          cat Cargo.toml
          echo '--- End Cargo.toml ---'

      - name: Commit and push if needed
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: auto-sort Cargo.toml dependencies [ci skip]"
          git push

  release:
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
    runs-on: windows-latest
    needs: [build]
    steps:
      - name: Set git to checkout as is, commit LF
        run: git config --global core.autocrlf input

      - uses: actions/checkout@v2

      - name: Compile Release
        run: cargo build --release

      - name: Github Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./target/release/wsl2-dns-agent.exe
